# !-----------------------------------------------------------------------------------------------!
#                          Welcome to the main configuration of the {name} plugin.
#                   This file is used to configure the plugin to your liking, please read carefully.
#                           If you have any questions, feel free to ask me on Discord:
#                                              @notmyidea
#                                         or open a github issue
# !-----------------------------------------------------------------------------------------------!

# See behavior.yml for detailed messages and configurations.
# This file supports most placeholders and all kinds of color codes.
# -----------------------------------------------------------
#                          General
# -----------------------------------------------------------
General:
  debugging: true

# -----------------------------------------------------------
#                          Economy
# -----------------------------------------------------------
Economy:
  # The Economy provider, set to "null" to disable any economic behavior
  provider: "uecon" # "vault" or "essentialsx", "cmi" or "uecon" 



# -----------------------------------------------------------
#                   Nation Configuration
# -----------------------------------------------------------
Nations:
  #
  # This part is for the creation of a Nation
  # /nation <create>
  Creation:
    #
    # are players allowed to create a nation?
    enabled: true
    required_permissions: "none" # "none" or "nations.create"
    #
    # How much does it cost to create a nation?
    # Requires an economy provider to be set in #Economy.provider
    cost: 1000
    #
    # This part is about the process of naming a Nation during its creation
    # /nation create <name>
    Naming:
        # Allows/Denies the use of color codes (&a,b,c) in Nation names, set to null to disable
        color_coding_permission: "nations.naming.colorcoding"
        # Maximum amount of characters for Nation names
        max_characters: 20
        # Minimum amount of characters for a Nation names
        min_characters: 3
        # Blacklisted names for Nations, can be multiple separated by commas
        blacklist: "admin,moderator,owner,staff,helper,dev,developer,admin,mod,moderator,owner,staff,helper,dev,developer,"
    Tags:
        # Maximum amount of characters for Nation tags
        max_characters: 4
        # Minimum amount of characters for a Nation tags
        min_characters: 2
        # Blacklisted tags for Nations, can be multiple separated by commas
        blacklist: "admin,moderator,owner,staff,helper,dev,developer,admin,mod,moderator,owner,staff,helper,dev,developer,"
    Description:
        color_coding_permission: "null"
        # Maximum amount of characters for Nation descriptions
        max_characters: 100
        # Minimum amount of characters for a Nation descriptions
        min_characters: 10
        # Blacklisted descriptions for Nations, can be multiple separated by commas
        blacklist: "admin,moderator,owner,staff,helper,dev,developer,admin,mod,moderator,owner,staff,helper,dev,developer,"
  #
  # This part is about the claiming of territory
  # It requires the player to be in a Nation
  # /nation <claim>
  Territory:
    Claiming:
      # Can Nations claim territory?
      enabled: true
      # How much does it cost to claim a chunk?
      cost: 100
      # Maximum amount of Chunks a Nation can claim
      max: 100
      # Minimum amount of Chunks a Nation can claim, will prevent the Nation from claiming 0
      min: 9

  #
  #
  #
  #
  #




